paths:
  data: "./data"
  raw: "${paths.data}/raw" 
  interim: "${paths.data}/interim"
  processed: "${paths.data}/processed"
  external: "${paths.data}/external"
  prediction: "${paths.data}/prediction"
  synthetic: "${paths.data}/synthetic"
  models: "./models"
  reports: "./reports"
  figures: "${paths.reports}/figures"

data:
  raw_data_file: "${paths.raw}/energy_modified.csv"
  interim_data_file: "${paths.interim}/energy_modified_clean.csv"
  processed_data:
    x_train_file: "${paths.processed}/Xtrain_processed.csv"
    x_test_file: "${paths.processed}/Xtest_processed.csv"
    y_train_file: "${paths.processed}/ytrain_processed.csv"
    y_test_file: "${paths.processed}/ytest_processed.csv"
  prediction_file: "${paths.prediction}/predictions.csv"
  synthetic_data_file: "${paths.synthetic}/synthetic_data.csv"
  mlflow_pid_file: "${paths.models}/mlflow.pid"

dvc:
  gdrive_remote_url: "${oc.env:GDRIVE_REMOTE_URL, ''}"
  gdrive_client_id: "${oc.env:GDRIVE_CLIENT_ID, ''}"
  gdrive_client_secret: "${oc.env:GDRIVE_CLIENT_SECRET, ''}"
  aws_remote_url: "${oc.env:AWS_REMOTE_URL, ''}"
  aws_region: "${oc.env:AWS_REGION, ''}"
  aws_profile: "${oc.env:AWS_PROFILE, ''}"

download:
  dataset_id: "1OuJHPpn2Wv5EhlL1J98HWYyPJM-iL8Ds"

cleaning:
  skew_threshold: 0.5

preprocessing:
  target_columns: ["Y1", "Y2"]
  feature_columns: ["X1", "X2", "X3", "X4", "X5", "X6", "X7", "X8"]
  allow_missing_columns: true
  test_size: 0.2
  random_state: 42
  target_transform: "yeo-johnson"
  encoding:
    drop: "first"
    sparse_output: false
    handle_unknown: "ignore"
  preprocessor_file: "${paths.models}/preprocessor.pkl"
  gmm_n_components: 8
  gmm_random_state: 42
  gmm_file: "${paths.models}/gmm.pkl"

synthetic:
  n_samples: 5000

training:
  mlflow_tracking_uri: "${oc.env:MLFLOW_TRACKING_URI, file:./mlruns}"
  random_state: 42
  rf_experiment_name: "rf_regressor"
  rf_registry_model_name: "RFRegressor"
  rf_model_path: "${paths.models}/${training.rf_experiment_name}"
  rf_model_file: "${training.rf_experiment_name}.pkl"
  xgb_experiment_name: "xgb_multioutput"
  xgb_registry_model_name: "XGBMultiOutput"
  xgb_model_path: "${paths.models}/${training.xgb_experiment_name}"
  xgb_model_file: "${training.xgb_experiment_name}.pkl"

prediction:
  use_model: "rf"
  use_version: "latest"

transform:
  target_method: "yeo-johnson"
  encoding:
    strategy: "onehot"
    drop: "first"
    handle_unknown: "ignore"
    sparse_output: false

metadata:
  author: "Equipo 38"
  project: "MLops_E38_F2"
  version: "1.0.0"